version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing pip..."
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Changing into template directory..."
      - cd template
      - echo "Installing Python requirements..."
      - pip install -r requirements.txt
      - echo "Fetching Docker Hub password from SSM..."
      - aws ssm get-parameters --name my_vault --with-decryption --query 'Parameters[0].Value' --output text > docker-hub-password.txt

  build:
    commands:
      - cd template
      - echo "Building Docker image..."
      - docker build -t shad .

  post_build:
    commands:
      - cd template
      - echo "Logging into Docker Hub..."
      - docker login -u shivopam -p $(cat docker-hub-password.txt)
      - echo "Tagging and pushing image..."
      - docker tag shad:latest shivopam/shad:latest
      - docker push shivopam/shad:latest
      - rm docker-hub-password.txt

artifacts:
  files:
    - '**/*'
