version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      python: 3.11
    commands:
      - echo "Installing pip and dependencies..."
      - pip install --upgrade pip
      - echo "Cloning the repo..."
      - git clone https://github.com/shivopam/Kube.git
      - cd Kube/template
      - echo "Installing Python requirements..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Fetching Docker Hub password from SSM..."
      - aws ssm get-parameters --name my_vault --with-decryption --query 'Parameters[0].Value' --output text > docker-hub-password.txt

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t shad .

  post_build:
    commands:
      - echo "Logging into Docker Hub..."
      - docker login -u shivopam -p $(cat docker-hub-password.txt)
      - echo "Tagging the Docker image..."
      - docker tag shad:latest shivopam/shad:latest
      - echo "Pushing Docker image to Docker Hub..."
      - docker push shivopam/shad:latest
      - rm docker-hub-password.txt

artifacts:
  files:
    - '**/*'
