version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t shad .

  post_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - aws ssm get-parameters --name docker-hub-password --with-decryption --query 'Parameters[0].Value' --output text > docker-hub-password.txt
      - docker login -u Shivopam -p $(cat docker-hub-password.txt)
      - echo "Pushing image to Docker Hub..."
      - docker tag shad:latest Shivopam/shad:latest
      - docker push Shivopam/shad:latest
      - rm docker-hub-password.txt  # Optional cleanup

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '**/node_modules/**'
